# Generated by Django 5.1.4 on 2025-04-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryitem_added_by_inventoryitem_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
